import 'dart:async';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import '../../../domain/entities/chat_message.dart';
import '../../../domain/repositories/chat_repository.dart';

part 'chat_room_event.dart';
part 'chat_room_state.dart';
part 'chat_room_bloc.freezed.dart';

class ChatRoomBloc extends Bloc<ChatRoomEvent, ChatRoomState> {
  final ChatRepository _chatRepository;
  StreamSubscription? _messagesSubscription;

  ChatRoomBloc({required ChatRepository chatRepository})
      : _chatRepository = chatRepository,
        super(const ChatRoomInitial()) {
    on<FetchMessages>(_onFetchMessages);
    on<MessagesUpdated>(_onMessagesUpdated);
    on<SendMessage>(_onSendMessage);
    on<MarkAsSeen>(_onMarkAsSeen);
  }

  Future<void> _onFetchMessages(FetchMessages event, Emitter<ChatRoomState> emit) async {
    emit(const ChatRoomLoading());
    await _messagesSubscription?.cancel();
    _messagesSubscription = _chatRepository.getMessages(event.roomId).listen(
      (messages) => add(MessagesUpdated(messages)),
      onError: (error) => add(const MessagesUpdated([])),
    );
  }

  void _onMessagesUpdated(MessagesUpdated event, Emitter<ChatRoomState> emit) {
    emit(ChatRoomLoaded(event.messages));
  }

  Future<void> _onSendMessage(SendMessage event, Emitter<ChatRoomState> emit) async {
    final message = ChatMessage(
      id: '', // Will be generated by Firebase
      senderId: event.senderId,
      text: event.text,
      timestamp: DateTime.now(),
      roomId: event.roomId,
    );
    await _chatRepository.sendMessage(event.roomId, message);
  }

  Future<void> _onMarkAsSeen(MarkAsSeen event, Emitter<ChatRoomState> emit) async {
    await _chatRepository.markAsSeen(event.userId, event.roomId);
  }

  @override
  Future<void> close() {
    _messagesSubscription?.cancel();
    return super.close();
  }
}
